# Generated by Django 4.0.6 on 2022-07-16 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('BTC', models.CharField(max_length=5)),
                ('ETH', models.CharField(max_length=5)),
                ('USDT', models.CharField(max_length=5)),
                ('USDC', models.CharField(max_length=5)),
                ('BNB', models.CharField(max_length=5)),
                ('BUSD', models.CharField(max_length=5)),
                ('XRP', models.CharField(max_length=5)),
                ('ADA', models.CharField(max_length=5)),
                ('SOL', models.CharField(max_length=5)),
                ('DOT', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
